# Generated by Django 4.0.1 on 2022-01-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envofertasmrt',
            name='Operador2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='envofertasmrt',
            name='prod_fim',
            field=models.CharField(choices=[('jan', 'JAN'), ('fev', 'FEV'), ('mar', 'MAR'), ('abr', 'ABR'), ('mai', 'MAI'), ('jun', 'JUN'), ('jul', 'JUL'), ('ago', 'AGO'), ('set', 'SET'), ('out', 'OUT'), ('nov', 'NOV'), ('dez', 'DEZ')], max_length=5),
        ),
        migrations.AlterField(
            model_name='envofertasmrt',
            name='prod_ini',
            field=models.CharField(choices=[('jan', 'JAN'), ('fev', 'FEV'), ('mar', 'MAR'), ('abr', 'ABR'), ('mai', 'MAI'), ('jun', 'JUN'), ('jul', 'JUL'), ('ago', 'AGO'), ('set', 'SET'), ('out', 'OUT'), ('nov', 'NOV'), ('dez', 'DEZ')], max_length=5),
        ),
    ]
