# Generated by Django 4.0.1 on 2022-02-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_envofertasmrt_operador2_alter_envofertasmrt_prod_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvOfertasMrtM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operador1', models.BooleanField(default=False)),
                ('Operador2', models.BooleanField(default=False)),
                ('tp_energia', models.CharField(choices=[('CONV', 'conv'), ('I5', 'i5'), ('I1', 'i1'), ('I0', 'i0'), ('CQ5', 'cq5')], max_length=5)),
                ('prod_ini', models.CharField(choices=[('jan', 'JAN'), ('fev', 'FEV'), ('mar', 'MAR'), ('abr', 'ABR'), ('mai', 'MAI'), ('jun', 'JUN'), ('jul', 'JUL'), ('ago', 'AGO'), ('set', 'SET'), ('out', 'OUT'), ('nov', 'NOV'), ('dez', 'DEZ')], max_length=5)),
                ('prod_fim', models.CharField(choices=[('jan', 'JAN'), ('fev', 'FEV'), ('mar', 'MAR'), ('abr', 'ABR'), ('mai', 'MAI'), ('jun', 'JUN'), ('jul', 'JUL'), ('ago', 'AGO'), ('set', 'SET'), ('out', 'OUT'), ('nov', 'NOV'), ('dez', 'DEZ')], max_length=5)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('submer', models.CharField(choices=[('SE', 'se'), ('SU', 'su'), ('NE', 'ne'), ('NO', 'no')], max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
