# Generated by Django 4.0.2 on 2022-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_envofertasmrtm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvOfertasMrt',
            new_name='BookCompra',
        ),
    ]
