# Generated by Django 4.0.2 on 2022-02-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_operador1_bookvenda_operador3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookvenda',
            old_name='Operador3',
            new_name='Operador1',
        ),
        migrations.RenameField(
            model_name='bookvenda',
            old_name='Operador4',
            new_name='Operador2',
        ),
    ]
