# Generated by Django 4.0.2 on 2022-02-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_bookcompra_operador_bookvenda_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompra',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
    ]
