# Generated by Django 4.0.2 on 2022-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_bookcompra_preco_alter_bookcompramerc_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcompramerc',
            name='Operador1',
        ),
        migrations.RemoveField(
            model_name='bookcompramerc',
            name='Operador2',
        ),
        migrations.RemoveField(
            model_name='bookvendamerc',
            name='Operador1',
        ),
        migrations.RemoveField(
            model_name='bookvendamerc',
            name='Operador2',
        ),
        migrations.AddField(
            model_name='bookcompramerc',
            name='Operador',
            field=models.CharField(choices=[('pedro', 'PEDRO'), ('raul', 'RAUL'), ('isabella', 'ISABELLA'), ('eduardo', 'EDUARDO'), ('aderson', 'ADERSON')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvendamerc',
            name='Operador',
            field=models.CharField(choices=[('pedro', 'PEDRO'), ('raul', 'RAUL'), ('isabella', 'ISABELLA'), ('eduardo', 'EDUARDO'), ('aderson', 'ADERSON')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcompra',
            name='Operador',
            field=models.CharField(choices=[('pedro', 'PEDRO'), ('raul', 'RAUL'), ('isabella', 'ISABELLA'), ('eduardo', 'EDUARDO'), ('aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcompra',
            name='submer',
            field=models.CharField(choices=[('se', 'SE'), ('su', 'SU'), ('ne', 'NE'), ('no', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bookcompra',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='submer',
            field=models.CharField(choices=[('se', 'SE'), ('su', 'SU'), ('ne', 'NE'), ('no', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='Operador',
            field=models.CharField(choices=[('pedro', 'PEDRO'), ('raul', 'RAUL'), ('isabella', 'ISABELLA'), ('eduardo', 'EDUARDO'), ('aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='submer',
            field=models.CharField(choices=[('se', 'SE'), ('su', 'SU'), ('ne', 'NE'), ('no', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='submer',
            field=models.CharField(choices=[('se', 'SE'), ('su', 'SU'), ('ne', 'NE'), ('no', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
    ]
