# Generated by Django 4.0.2 on 2022-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_bookcompramerc_operador1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompra',
            name='Operador',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='Operador',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='Operador',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='Operador',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
    ]
