# Generated by Django 3.2.2 on 2022-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_bookcompra_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompra',
            name='Operador',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
