# Generated by Django 4.0.2 on 2022-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_bookcompra_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcompramerc',
            name='agente',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvendamerc',
            name='agente',
            field=models.CharField(choices=[('Pedro', 'PEDRO'), ('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
