# Generated by Django 4.0.2 on 2022-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_bookcompramerc_agente_bookvendamerc_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompramerc',
            name='agente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='agente',
            field=models.CharField(max_length=50),
        ),
    ]
