# Generated by Django 4.0.3 on 2022-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_bookcompra_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompramerc',
            name='Operador',
            field=models.CharField(choices=[('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='Operador',
            field=models.CharField(choices=[('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='Operador',
            field=models.CharField(choices=[('Raul', 'RAUL'), ('Isabella', 'ISABELLA'), ('Eduardo', 'EDUARDO'), ('Aderson', 'ADERSON')], max_length=50),
        ),
    ]
