# Generated by Django 4.0.3 on 2022-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_bookcompramerc_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcompra',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
