# Generated by Django 4.0.3 on 2022-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_bookcompra_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvenda',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
