# Generated by Django 4.0.3 on 2022-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_bookvenda_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompra',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
