# Generated by Django 3.2.2 on 2022-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_bookcompra_checked_alter_bookvenda_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompra',
            name='tp_energia',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='tp_energia',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='tp_energia',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='tp_energia',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], max_length=5),
        ),
    ]
