# Generated by Django 4.0.3 on 2022-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20220505_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcompra',
            name='tp_preco',
            field=models.CharField(blank=True, choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bookcompramerc',
            name='tp_preco',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvenda',
            name='tp_preco',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvendamerc',
            name='tp_preco',
            field=models.CharField(choices=[('Fixo', 'FIXO'), ('Pld', 'PLD')], default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcompra',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookcompramerc',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvenda',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvendamerc',
            name='tp_energia',
            field=models.CharField(choices=[('conv', 'CONV'), ('i5', 'I5'), ('i1', 'I1'), ('i0', 'I0'), ('cq5', 'CQ5')], max_length=5),
        ),
    ]
