# Generated by Django 4.0.4 on 2022-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_remove_bookcompramerc_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcompramerc',
            name='agente',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvendamerc',
            name='agente',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
